### ISSUE TITLE
Не получается отправить заказ с сайт в 1с 

### ISSUE THREAD

**Issue by devig** [kilylabs/odata-1c#4]
$data = $client->{'Document_ЗаказКлиента'}->get()->values();//получаю заказ, ниже его привожу

//далее удаляю ключи
unset($data[0]['Ref_Key']);
unset($data[0]['Товары'][0]['Ref_Key']);
unset($data[0]['DataVersion']);
unset($data[0]['ЭтапыГрафикаОплаты'][0]['Ref_Key']);

//отправляю
$result = $client->{'Document_ЗаказКлиента'}->create($data[0]);
// отвечает 500 
/*
"odata.error": {
"code": "-1",
"message": {
"lang": "ru",
"value": "Ошибка при выполнении обработчика - 'ОбработкаЗаполнения'"
}
}
*/
Цель создать заказ в 1с. Что делаю не так? 

Array
(
    [Ref_Key] => 1711a01c-b507-11e7-82e4-dc85de068416
    [DataVersion] => AAAAAAAERK0=
    [DeletionMark] => 
    [Number] => 0000-000001
    [Date] => 2017-10-19T22:52:52
    [Posted] => 1
    [Партнер_Key] => f086a25f-e54d-11e6-be4c-c4aaa95c8a87
    [Контрагент_Key] => f086a260-e54d-11e6-be4c-c4aaa95c8a87
    [Организация_Key] => 7023ff84-e51f-11e6-be4c-c4aaa95c8a87
    [Соглашение_Key] => d83f0987-b4fd-11e7-82e4-dc85de068416
    [Сделка_Key] => 00000000-0000-0000-0000-000000000000
    [Валюта_Key] => 51c5ae5c-e3ff-11e6-b7ce-db9992ffcc86
    [СуммаДокумента] => 1
    [ГрафикОплаты_Key] => 00000000-0000-0000-0000-000000000000
    [ЖелаемаяДатаОтгрузки] => 0001-01-01T00:00:00
    [Склад_Key] => 93235842-57fc-11e7-82db-dc85de068416
    [ЦенаВключаетНДС] => 
    [Менеджер_Key] => f086a25a-e54d-11e6-be4c-c4aaa95c8a87
    [ДополнительнаяИнформация] => 
    [ДокументОснование] => 
    [ДокументОснование_Type] => StandardODATA.Undefined
    [НеОтгружатьЧастями] => 1
    [Статус] => КОбеспечению
    [МаксимальныйКодСтроки] => 1
    [ДатаСогласования] => 2017-10-19T00:00:00
    [Согласован] => 1
    [ФормаОплаты] => 
    [БанковскийСчет_Key] => 5207248a-e70d-11e6-82d3-dc85de068416
    [БанковскийСчетКонтрагента_Key] => 00000000-0000-0000-0000-000000000000
    [Касса_Key] => 00000000-0000-0000-0000-000000000000
    [СуммаАвансаДоОбеспечения] => 0
    [СуммаПредоплатыДоОтгрузки] => 1
    [ДатаОтгрузки] => 2017-10-20T00:00:00
    [АдресДоставки] => 
    [НалогообложениеНДС] => ПродажаНеОблагаетсяНДС
    [СкидкиРассчитаны] => 1
    [ХозяйственнаяОперация] => РеализацияКлиенту
    [Комментарий] => 
    [НомерПоДаннымКлиента] => 
    [ДатаПоДаннымКлиента] => 0001-01-01T00:00:00
    [Грузоотправитель_Key] => 00000000-0000-0000-0000-000000000000
    [Грузополучатель_Key] => 00000000-0000-0000-0000-000000000000
    [БанковскийСчетГрузоотправителя_Key] => 00000000-0000-0000-0000-000000000000
    [БанковскийСчетГрузополучателя_Key] => 00000000-0000-0000-0000-000000000000
    [ГруппаФинансовогоУчета_Key] => 00000000-0000-0000-0000-000000000000
    [КартаЛояльности_Key] => 00000000-0000-0000-0000-000000000000
    [Договор_Key] => 00000000-0000-0000-0000-000000000000
    [Подразделение_Key] => 00000000-0000-0000-0000-000000000000
    [Автор] => f086a25a-e54d-11e6-be4c-c4aaa95c8a87
    [Автор_Type] => UnavailableEntities.UnavailableEntity_604931cd-d4a8-48d0-bc59-2ac90e044abb
    [ПорядокРасчетов] => ПоЗаказамНакладным
    [Назначение_Key] => 00000000-0000-0000-0000-000000000000
    [СпособДоставки] => Самовывоз
    [ПеревозчикПартнер_Key] => 00000000-0000-0000-0000-000000000000
    [ЗонаДоставки_Key] => 00000000-0000-0000-0000-000000000000
    [ВремяДоставкиС] => 0001-01-01T00:00:00
    [ВремяДоставкиПо] => 0001-01-01T00:00:00
    [АдресДоставкиПеревозчика] => 
    [АдресДоставкиЗначенияПолей] => 
    [АдресДоставкиПеревозчикаЗначенияПолей] => 
    [ДополнительнаяИнформацияПоДоставке] => 
    [КонтактноеЛицо_Key] => 00000000-0000-0000-0000-000000000000
    [Руководитель_Key] => 00000000-0000-0000-0000-000000000000
    [ГлавныйБухгалтер_Key] => 00000000-0000-0000-0000-000000000000
    [ВернутьМногооборотнуюТару] => 
    [СрокВозвратаМногооборотнойТары] => 0
    [СостояниеЗаполненияМногооборотнойТары] => 
    [СуммаВозвратнойТары] => 0
    [НазначениеПлатежа] => 
    [ТребуетсяЗалогЗаТару] => 
    [Приоритет_Key] => 743a8857-e3ff-11e6-b7ce-db9992ffcc86
    [ИдентификаторПлатежа] => ЗК171000000000010006
    [ОсобыеУсловияПеревозки] => 
    [ОсобыеУсловияПеревозкиОписание] => 
    [НаправлениеДеятельности_Key] => 00000000-0000-0000-0000-000000000000
    [ПорядокОплаты] => РасчетыВРубляхОплатаВРублях
    [Товары] => Array
        (
            [0] => Array
                (
                    [Ref_Key] => 1711a01c-b507-11e7-82e4-dc85de068416
                    [LineNumber] => 1
                    [ДатаОтгрузки] => 2017-10-20T00:00:00
                    [Номенклатура_Key] => 235e1343-5ca0-11e7-82df-dc85de068416
                    [Характеристика_Key] => 00000000-0000-0000-0000-000000000000
                    [Упаковка_Key] => 00000000-0000-0000-0000-000000000000
                    [КоличествоУпаковок] => 1
                    [Количество] => 1
                    [ВидЦены_Key] => 00000000-0000-0000-0000-000000000000
                    [Цена] => 1
                    [Сумма] => 1
                    [СтавкаНДС] => БезНДС
                    [СуммаНДС] => 0
                    [СуммаСНДС] => 1
                    [ПроцентРучнойСкидки] => 0
                    [СуммаРучнойСкидки] => 0
                    [ПроцентАвтоматическойСкидки] => 0
                    [СуммаАвтоматическойСкидки] => 0
                    [ПричинаОтмены_Key] => 00000000-0000-0000-0000-000000000000
                    [КодСтроки] => 1
                    [Отменено] => 
                    [КлючСвязи] => 1
                    [Склад_Key] => 93235842-57fc-11e7-82db-dc85de068416
                    [СрокПоставки] => 0
                    [Содержание] => 
                    [СтатусУказанияСерий] => 0
                    [ВариантОбеспечения] => Требуется
                    [Серия_Key] => 00000000-0000-0000-0000-000000000000
                    [НоменклатураНабора_Key] => 00000000-0000-0000-0000-000000000000
                    [ХарактеристикаНабора_Key] => 00000000-0000-0000-0000-000000000000
                    [ЦенаСоСкидкой] => 0
                    [Скидка] => 0
                )

        )

    [ЭтапыГрафикаОплаты] => Array
        (
            [0] => Array
                (
                    [Ref_Key] => 1711a01c-b507-11e7-82e4-dc85de068416
                    [LineNumber] => 1
                    [ВариантОплаты] => ПредоплатаДоОтгрузки
                    [ДатаПлатежа] => 2017-10-19T00:00:00
                    [ПроцентПлатежа] => 100
                    [СуммаПлатежа] => 1
                    [ПроцентЗалогаЗаТару] => 0
                    [СуммаЗалогаЗаТару] => 0
                    [СуммаОтклоненияМерныхТоваров] => 0
                )

        )

    [СкидкиНаценки] => Array
        (
        )

    [ДополнительныеРеквизиты] => Array
        (
        )

)

**Comment by ab-kily** [comment]
@devig, сложно сказать, ведь обязательные поля при создании какого-либо объекта всегда индивидуальны для используемой конфигурации 1С. Привожу пример создания заказа для УТ 11:
```php
$odata = array (
  'Number' => 'ORDER-NB-128938',
  'Date' => '2019-05-15T09:27:51+03:00',
  'ЖелаемаяДатаОтгрузки' => '2019-05-15T00:00:00+03:00',
  'ДатаОтгрузки' => '2019-05-15T00:00:00+03:00',
  'Организация_Key' => '2b3e8ebe-c1c2-11e6-d495-00155dd9fc47',
  'Партнер_Key' => '473eac84-c1b3-11e6-3b95-00155dd9fc47',
  'Контрагент_Key' => '335e9bcc-76ea-11e9-ce91-4110cd835450',
  'Соглашение_Key' => 'd8e27e68-c370-11e6-d495-00155dd9fc47',
  'Сделка_Key' => '00000000-0000-0000-0000-000000000000',
  'Валюта_Key' => 'ec4378f4-c1b3-11e6-3b95-00155dd9fc47',
  'СуммаДокумента' => 28990.0,
  'ГрафикОплаты_Key' => '00000000-0000-0000-0000-000000000000',
  'Склад_Key' => '4a1b565a-c1c2-11e6-d495-00155dd9fc47',
  'Менеджер_Key' => '3df9babc-1042-11e9-2580-3561ecf9b9a1',
  'НеОтгружатьЧастями' => true,
  'Статус' => 'КОбеспечению',
  'МаксимальныйКодСтроки' => 2,
  'ПорядокОплаты' => 'РасчетыВРубляхОплатаВРублях',
  'ЭтапыГрафикаОплаты' => 
  array (
    0 => 
    array (
      'LineNumber' => '1',
      'ВариантОплаты' => 'КредитПослеОтгрузки',
      'ДатаПлатежа' => '2019-05-15T00:00:00+03:00',
      'ПроцентПлатежа' => 100,
      'СуммаПлатежа' => 28990.0,
      'ПроцентЗалогаЗаТару' => 0,
      'СуммаЗалогаЗаТару' => 0,
    ),
  ),
  'Товары' => 
  array (
    0 => 
    array (
      'LineNumber' => 1,
      'КодСтроки' => 1,
      'ДатаОтгрузки' => '2019-05-15T00:00:00+03:00',
      'Номенклатура_Key' => '40366f94-cded-11e6-e880-00155dd9fc47',
      'Характеристика_Key' => '00000000-0000-0000-0000-000000000000',
      'Упаковка_Key' => '00000000-0000-0000-0000-000000000000',
      'КоличествоУпаковок' => '1',
      'Содержание' => 'Куртка пух муж BASK TAIMYR',
      'Количество' => '1',
      'ВидЦены' => 'b9bb5abe-c370-11e6-d495-00155dd9fc47',
      'СтавкаНДС' => 'БезНДС',
      'СуммаНДС' => 0,
      'Цена' => '28990',
      'Сумма' => 28990.0,
      'СуммаСНДС' => 28990.0,
      'ПроцентРучнойСкидки' => '0',
      'СуммаРучнойСкидки' => '0.00',
      'Склад_Key' => '4a1b565a-c1c2-11e6-d495-00155dd9fc47',
      'ВариантОбеспечения' => 'Отгрузить',
    ),
    1 => 
    array (
      'LineNumber' => 2,
      'КодСтроки' => 2,
      'ДатаОтгрузки' => '2019-05-15T00:00:00+03:00',
      'Номенклатура_Key' => '0bb4403c-d0f6-11e6-2786-00155dd9fc47',
      'Характеристика_Key' => '00000000-0000-0000-0000-000000000000',
      'Упаковка_Key' => '00000000-0000-0000-0000-000000000000',
      'КоличествоУпаковок' => 1,
      'Количество' => 1,
      'ВидЦены' => '00000000-0000-0000-0000-000000000000',
      'СтавкаНДС' => 'БезНДС',
      'СуммаНДС' => 0,
      'Цена' => '0',
      'ПроцентРучнойСкидки' => 0,
      'СуммаРучнойСкидки' => 0,
      'Сумма' => 0,
      'СуммаСНДС' => 0,
      'ВариантОбеспечения' => 'Отгрузить',
      'Содержание' => 'Самовывоз',
    ),
  ),
);
$data = $client->{'Document_ЗаказКлиента'}->create($odata);
if(!$client->isOk()) {
    var_dump($id,$odata,$client->getErrorCode(),$client->getErrorMessage());
    return false;
} else {
    if(!$id) $id = $client->getLastId();
    ...
}
```
